// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0QiG7PyxKc_wwF48cY94UuSmDvHEMWr8',
    appId: '1:811775765580:web:561542f222a805acb698e9',
    messagingSenderId: '811775765580',
    projectId: 'expense-tracker-dev-d39f8',
    authDomain: 'expense-tracker-dev-d39f8.firebaseapp.com',
    storageBucket: 'expense-tracker-dev-d39f8.appspot.com',
    measurementId: 'G-6GEBNK244V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFLdHq7_H6-suJpFZ-JbxICyPAgY1BKHY',
    appId: '1:811775765580:android:0fb2c00fa028894ab698e9',
    messagingSenderId: '811775765580',
    projectId: 'expense-tracker-dev-d39f8',
    storageBucket: 'expense-tracker-dev-d39f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJdDY6GKVdlXoguAKfKicZIGdtycDOq7s',
    appId: '1:811775765580:ios:d23d98dc0e7ea2f2b698e9',
    messagingSenderId: '811775765580',
    projectId: 'expense-tracker-dev-d39f8',
    storageBucket: 'expense-tracker-dev-d39f8.appspot.com',
    iosClientId:
        '811775765580-b4ve49ljg0adc5bc5j211na4ei6at6sl.apps.googleusercontent.com',
    iosBundleId: 'com.quydn720.expenseTracker.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJdDY6GKVdlXoguAKfKicZIGdtycDOq7s',
    appId: '1:811775765580:ios:d23d98dc0e7ea2f2b698e9',
    messagingSenderId: '811775765580',
    projectId: 'expense-tracker-dev-d39f8',
    storageBucket: 'expense-tracker-dev-d39f8.appspot.com',
    iosClientId:
        '811775765580-b4ve49ljg0adc5bc5j211na4ei6at6sl.apps.googleusercontent.com',
    iosBundleId: 'com.quydn720.expenseTracker.dev',
  );
}
