// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJMs5ycoVmWLrATtjlCQ0d4yI1EprtlQo',
    appId: '1:670595673481:web:a769efde5d08b668fbc558',
    messagingSenderId: '670595673481',
    projectId: 'expense-tracker-9d9aa',
    authDomain: 'expense-tracker-9d9aa.firebaseapp.com',
    storageBucket: 'expense-tracker-9d9aa.appspot.com',
    measurementId: 'G-QPRX5X42KS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8ltzpBA7CkIjhp0Ajqt2TQUtfxgLRKl4',
    appId: '1:670595673481:android:41e94da92cce74ddfbc558',
    messagingSenderId: '670595673481',
    projectId: 'expense-tracker-9d9aa',
    storageBucket: 'expense-tracker-9d9aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMv9WN6YYPpw_IZWFUxGpx-5rdl3rgmfE',
    appId: '1:670595673481:ios:b7f86587e9f79b6cfbc558',
    messagingSenderId: '670595673481',
    projectId: 'expense-tracker-9d9aa',
    storageBucket: 'expense-tracker-9d9aa.appspot.com',
    androidClientId:
        '670595673481-4cfgrobmcbdnc06l60u31d0kl8pc3nei.apps.googleusercontent.com',
    iosClientId:
        '670595673481-9en1gpmt9ljrgoit6fp9oegp4l230rca.apps.googleusercontent.com',
    iosBundleId: 'com.quydn720.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMv9WN6YYPpw_IZWFUxGpx-5rdl3rgmfE',
    appId: '1:670595673481:ios:b7f86587e9f79b6cfbc558',
    messagingSenderId: '670595673481',
    projectId: 'expense-tracker-9d9aa',
    storageBucket: 'expense-tracker-9d9aa.appspot.com',
    androidClientId:
        '670595673481-4cfgrobmcbdnc06l60u31d0kl8pc3nei.apps.googleusercontent.com',
    iosClientId:
        '670595673481-9en1gpmt9ljrgoit6fp9oegp4l230rca.apps.googleusercontent.com',
    iosBundleId: 'com.quydn720.expenseTracker',
  );
}
